Models/Domain/Auction/Application.cs
using Models.Domain.Base;
using Models.Domain.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Domain.Auction
{
    public class Application : UserModel
    {
        public int Id { get; set; }
     
        [StringLength(50)]
        public string AIN { get; set; }

        [ForeignKey("Customer")]
        public int CustomerId { get; set; }
        public virtual User Customer { get; set; }

        [ForeignKey("SeriesCategory")]
        public int SeriesCategoryId { get; set; }
        public virtual SeriesCategory SeriesCategory { get; set; }

        [ForeignKey("Series")]
        public int SeriesId { get; set; }
        public virtual Series Series { get; set; }

        [ForeignKey("SeriesNumber")]
        public int SeriesNumberId { get; set; }
        public virtual SeriesNumber SeriesNumber { get; set; }

        [Required]
        [StringLength(50)]
        public string ChasisNumber { get; set; }

        [Required]
        [StringLength(70)]
        public string OwnerName { get; set; }

        [ForeignKey("ApplicationStatus")]
        public int ApplicationStatusId { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
    }
}

Models/Views/Auction/Application.cs
using Models.Views.Bank;
using Models.Views.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Models.Views.Auction
{
    public class Application : Paging
    {
        public int Id { get; set; }

        public string AIN { get; set; }

        public int CustomerId { get; set; }
        public string Customer { get; set; }

        public int SeriesCategoryId { get; set; }
        public string SeriesCategory { get; set; }

        public int SeriesId { get; set; }
        public string Series { get; set; }

        public int SeriesNumberId { get; set; }

        [Display(Name = "Registration Mark")]
        public string SeriesNumber { get; set; }
        public int ReservePrice { get; set; }

        //[Required]
        [StringLength(50)]
        public string ChasisNumber { get; set; }

        //[Required]
        [StringLength(70)]
        public string OwnerName { get; set; }

        [StringLength(20)]
        public string PSId { get; set; }

        public int PaymentStatusId { get; set; }

        public DateTime? PaidOn { get; set; }

        public int ApplicationStatusId { get; set; }
        public string ApplicationStatus { get; set; }

        public DateTime RegStartDateTime { get; set; }
        public DateTime RegEndDateTime { get; set; }

        public DateTime AuctionStartDateTime { get; set; }
        public DateTime AuctionEndDateTime { get; set; }

        public int RemainingTime { get; set; }

        public List<ApplicationStatusHistory> ApplicationStatusHistory { get; set; }

        public AppSecurityDeposit AppSecurityDeposit { get; set; }
    }
}

Models/Views/Auction/Winners.cs
using System;

namespace Models.Views.Auction
{
    public class Winners
    {
        public int ApplicationId { get; set; }
        public string ApplicationStatus { get; set; }
        public DateTime AuctionEndDateTime { get; set; }
        public string YourAIN { get; set; }
        public string SeriesCategory { get; set; }
        public int SeriesCategoryId { get; set; }
        public int SeriesId { get; set; }
        public string Series { get; set; }
        public string SeriesNumber { get; set; }
        public int SeriesNumberId { get; set; }
        public int ReservePrice { get; set; }
        public int YourHighestBiddingPrice { get; set; }
        public int HighestBiddingPrice { get; set; }
        public string WinnerAIN { get; set; }
        public string WinnerChasisNumber { get; set; }
        public string ChasisNumber { get; set; }
        public string OwnerName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FatherHusbandName { get; set; }
        public string CNIC { get; set; }
        public string NTN { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
    }
}

Models/Views/Input/Application.cs
using System.ComponentModel.DataAnnotations;

namespace Models.Views.Input
{
    public class Application
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Chassis Number")]
        public string ChasisNumber { get; set; }

        [Required]
        [StringLength(70)]
        [Display(Name = "Vehicle Owner Name")]
        public string OwnerName { get; set; }
    }
}

Models/Views/Reports/Application.cs
namespace Models.Views.Reports
{
    public class Application
    {
        public string SeriesCategory { get; set; }
        public string SeriesName { get; set; }
        public string AuctionNumber { get; set; }
        public int ReservePrice { get; set; }
        public string AIN { get; set; }
        public string MRA { get; set; }
        public string CreatedOn { get; set; }
        public int Count { get; set; }
    }
}

Controllers/LOVController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using eauction.Data;
using eauction.SignalR;
using Microsoft.AspNetCore.SignalR;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using NotificationServices;
using Models.Domain.Auction;
using System;
using System.Linq;

namespace eauction.Controllers
{
    public class LOVController : BaseController
    {
        private readonly IHubContext<NotificationHub> notificationHub;
        private readonly IWebHostEnvironment webHostEnvironment;

        public LOVController(ILogger<HomeController> logger,
            IConfiguration configuration,
            ApplicationDbContext applicationDbContext,
            IHubContext<NotificationHub> hub,
            //ISmsSender smsSender,
            INotificationManager notificationManager,
            IWebHostEnvironment env)
                : base(logger, configuration, applicationDbContext, notificationManager)
        {
            //base(logger, configuration);
            this.notificationHub = hub;
            this.webHostEnvironment = env;
        }

        public Task<JsonResult> GetSeries(int seriesCategoryId)
        {
            try
            {
                var ds = this.AuctionService.GetSeries(seriesCategoryId);

                var series = Infrastructure.DataTableExtension.DataTableToList<Models.Views.Auction.Series>(ds.Tables[0])
                    .Where(x => x.SeriesStatusId != 5 && x.AuctionEndDateTime < DateTime.Now)  //   5 = Series Closed
                    .Select(x => new 
                    {
                        x.Id,
                        x.SeriesName
                    })
                    .ToList();

                return Task.FromResult(new JsonResult(new
                {
                    status = true,
                    series
                }));
            }
            catch
            {
                return this.Error();
            }
        }

        public Task<JsonResult> GetSeriesAll(int seriesCategoryId)
        {
            try
            {
                var ds = this.AuctionService.GetSeries(seriesCategoryId);

                var series = Infrastructure.DataTableExtension.DataTableToList<Models.Views.Auction.Series>(ds.Tables[0])
                    //.Where(x => x.SeriesStatusId != 5 && x.AuctionEndDateTime < DateTime.Now)  //   5 = Series Closed
                    .Select(x => new
                    {
                        x.Id,
                        x.SeriesName
                    })
                    .ToList();

                return Task.FromResult(new JsonResult(new
                {
                    status = true,
                    series
                }));
            }
            catch
            {
                return this.Error();
            }
        }

        private Task<JsonResult> Error()
        {
            return Task.FromResult(new JsonResult(new
            {
                status = false,
                msg = "Error",
            }));
        }
    }
}

Views/Admin/EditSeries.cshtml
@model Models.Views.Auction.Series

@{
    ViewData["Title"] = "Add/ Edit Series";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .custom-select {
        padding: 0px 0px 0px 0px;
        margin: 0px 0px 0px 0px;
    }

    .form-group label {
        padding: 5px 0px 0px 0px;
    }

    .toUpper {
        text-transform: uppercase;
    }
</style>

<div class="content-area col-sm-9">
    @if (TempData.Count > 0)
    {
        if (TempData["Error"] != null)
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> @TempData["Error"]
            </div>
        }
    }
    <div class="detail-block">
        <h1>Add/ Edit Series</h1>
        <div class="auction-block">
            <form asp-action="SaveSeries">
                <input type="hidden" asp-for="Id" />
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Category</label>
                            <div class="col-md-6">
                                <select class="form-control custom-select" asp-for="CategoryId" asp-items="ViewBag.SeriesCategorySelectList"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Series</label>
                            <div class="col-md-6">
                                <input class="form-control toUpper" asp-for="SeriesName" />
                                <span asp-validation-for="SeriesName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Reg. Start Date Time</label>
                            <div class="col-md-6">
                                <input class="form-control" asp-for="RegStartDateTime" />
                                <span asp-validation-for="RegStartDateTime" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Reg. End Date Time</label>
                            <div class="col-md-6">
                                <input class="form-control" asp-for="RegEndDateTime" />
                                <span asp-validation-for="RegEndDateTime" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Auction Start Date Time</label>
                            <div class="col-md-6">
                                <input class="form-control" asp-for="AuctionStartDateTime" />
                                <span asp-validation-for="AuctionStartDateTime" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Auction End Date Time</label>
                            <div class="col-md-6">
                                <input class="form-control" asp-for="AuctionEndDateTime" />
                                <span asp-validation-for="AuctionEndDateTime" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right">Is Reauctioning ?</label>
                            <div class="col-md-6">
                                <input class="form-control" asp-for="IsReauctioning" />
                                <span asp-validation-for="IsReauctioning" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <br />

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 text-right"></label>
                            <div class="col-md-6">
                                <input type="submit" class="btn-login" value="Save" />
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Admin/FindApplications_0.cshtml
@model IEnumerable<Models.Views.Auction.Application>

@{
    ViewData["Title"] = "Bidding Applications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <script src="~/lib/Custom/sweetalert.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("input[name=searchBtn]").click(function () {

                $.ajax({
                    url: "/Admin/FindApplications",
                    data: { ApplicationStatusId: $("#applicationStatusId").val(), AIN: $("#AIN").val() },
                    success: function (response) {
                        $("div.table-responsive").html(response);
                    },
                    failure: function (response) {
                        swal("Request Error!", "Request Error , Please try again latter." + response, "error");
                    }
                });
            });
        });
    </script>
}
<div class="content-area col-sm-9">
    <div class="detail-block">
        <h1>Customers' Applications</h1>

        @*<div class="alert alert-info" role="alert">
            
        </div>
        <div class="auction-block">
        </div>*@

        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-3 push-right">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">Search</a>
                            </h4>
                        </div>
                    </div>
                </div>
                <div id="collapse1" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-md-4">Status</label>
                                    <div class="col-md-8">
                                        <select id="applicationStatusId" asp-items="ViewBag.ApplicationStatus"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-md-4">AIN</label>
                                    <div class="col-md-8">
                                        <input type="text" id="AIN" name="AIN" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <input type="button" class="btn btn-sm btn-default" name="searchBtn" value="Search" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
<div class="content-area col-sm-9">
    <div class="detail-block">
        @*<h1>Bidding Applications</h1>*@
        <div class="auction-block">
            <div class="table-responsive">
                <partial name="_Applications" model="Model" />
            </div>
        </div>
    </div>
</div>

Views/Admin/GetApplicationsApproved.cshtml
@model IEnumerable<Models.Views.Reports.Application>

@{
    ViewData["Title"] = "Winners";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    option.active {
        display: inline-block;
    }

    option.inactive {
        display: none;
    }
</style>

@section Scripts
{
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <script src="~/lib/Custom/sweetalert.min.js"></script>

    <script type="text/javascript">

        function bindSelectLists(targetControl, data, dataIDField, dataTextField, addDefault, defaultText, selectedValue) {
            $(targetControl).find('option')
                .remove();

            if (defaultText === undefined || defaultText === null) {
                defaultText = 'Choose your option';
            }

            if (addDefault)
                $(targetControl).append($("<option />").val('').text(defaultText));

            $.each(data, function (index, value) {
                $(targetControl).append($("<option />").val(this[dataIDField]).text(this[dataTextField]));
            });
        }

        $(document).ready(function () {

            $(document).on('change', '#SeriesCategoryId', function (event) {

                $("#loader").toggle();

			var val = $(this).val();

                $.get("@Url.Action("GetSeriesAll", "LOV")", { seriesCategoryId: val }, function (response) {

                    bindSelectLists($('#SeriesId'), response.series, 'id', 'seriesName', true, 'All');

			}, "json").fail(function (error) {
				console.log(error);
            })
                    .done(function () {
                        $("#loader").toggle();
                    });

		});

            $("input[name=searchBtn]").click(function () {

                fetch();
            });

            function fetch() {

                $("#loader").toggle();

                $.ajax({
                    url: "/Admin/GetApplicationsApproved",
                    data: {
                        SeriesCategoryId: $("#SeriesCategoryId").val(),
                        SeriesId: $("#SeriesId").val()
                    },
                    success: function (response) {
                        $("div.table-responsive").html(response);
                    },
                    failure: function (response) {
                        swal("Request Error!", "Request Error , Please try again latter." + response, "error");
                    }
                })
                    .done(function () {
                        $("#loader").toggle();
                    });
            }

        });
    </script>
}
<div class="content-area col-sm-9">
    <div class="detail-block">
        <h1>Approved Applications</h1>
        <br />
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-3 push-right">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">Search</a>
                            </h4>
                        </div>
                    </div>
                </div>
                <div id="collapse1" class="panel-collapse collapse in">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-12">
                                <label class="col-md-3 text-right field-lable">Category</label>
                                <div class="col-md-6">
                                    <select id="SeriesCategoryId" asp-items="ViewBag.SeriesCategory">
                                        <option>All</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <label class="col-md-3 text-right field-lable">Series</label>
                                <div class="col-md-6">
                                    <select id="SeriesId">
                                        <option>All</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-4">
                                        <br />
                                        <input type="button" class="btn-login" name="searchBtn" value="Search" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                    </div>
                    <div class="panel-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
<div class="content-area col-sm-9">
    <div class="detail-block">
        <div class="auction-block">
            <div class="table-responsive">
                <partial name="_ApplicationsApproved" model="Model" />
            </div>
        </div>
    </div>
</div>

Views/Admin/GetNotifications.cshtml
@model IEnumerable<Models.Views.Notification.Notification>

@{
    ViewData["Title"] = "Notifications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-area col-sm-9">
    <div class="detail-block">
        <h1>Notifications</h1>
        <br />
        <a class="btn btn-sm btn-primary" asp-action="GetNotificationDetail" asp-route-notificationId="0">Create New</a>
        <div class="auction-block">
        <br />
            <div class="table-responsive">
                <table class="registration-table add other">
                    <tr>
                        <th></th>
                        <th>Heading</th>
                        <th>Content</th>
                        <th>Data</th>
                        <th>Dated</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                        @{
                            int rowNum = 0;
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@{ rowNum++; } @rowNum</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Heading)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Content)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Data)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedOn)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotificationStatus)
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "GetNotificationDetail", new { notificationId = item.Id }, htmlAttributes: new { @class = "btn-select" })
                                </td>
                            </tr>
                        }
                </table>
            </div>
        </div>
    </div>
</div>

Views/Admin/GetWinnersSeriesWise.cshtml
@model IEnumerable<Models.Views.Auction.Winners>

@{
    ViewData["Title"] = "Winners";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    option.active {
        display: inline-block;
    }

    option.inactive {
        display: none;
    }
</style>

@section Scripts
{
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <script src="~/lib/Custom/sweetalert.min.js"></script>

    <script type="text/javascript">

        function bindSelectLists(targetControl, data, dataIDField, dataTextField, addDefault, defaultText, selectedValue) {
            $(targetControl).find('option')
                .remove();

            if (defaultText === undefined || defaultText === null) {
                defaultText = 'Choose your option';
            }

            if (addDefault)
                $(targetControl).append($("<option />").val('').text(defaultText));

            $.each(data, function (index, value) {
                $(targetControl).append($("<option />").val(this[dataIDField]).text(this[dataTextField]));
            });
        }

        $(document).ready(function () {

            $(document).on('change', '#SeriesCategoryId', function (event) {

                $("#loader").toggle();

			var val = $(this).val();

                $.get("@Url.Action("GetSeries", "LOV")", { seriesCategoryId: val }, function (response) {

                    bindSelectLists($('#SeriesId'), response.series, 'id', 'seriesName', true, 'Select...');

			}, "json").fail(function (error) {
				console.log(error);
            })
                    .done(function () {
                        $("#loader").toggle();
                    });

		});

            $("input[name=searchBtn]").click(function () {

                fetch();
            });

            function fetch() {

                $("#loader").toggle();

                $.ajax({
                    url: "/Admin/GetWinnersSeriesWise",
                    data: {
                        SeriesId: $("#SeriesId").val()
                    },
                    success: function (response) {
                        $("div.table-responsive").html(response);
                    },
                    failure: function (response) {
                        swal("Request Error!", "Request Error , Please try again latter." + response, "error");
                    }
                })
                    .done(function () {
                        $("#loader").toggle();
                    });
            }
        });
    </script>
}
<div class="content-area col-sm-9">
    @if (TempData.Count > 0)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Success!</strong> Winners list approved successfully for @TempData["ApprovedSeries"]
        </div>
    }
    <div class="detail-block">
        <h1>Approval of Winners List</h1>
        <br />
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-3 push-right">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">Search</a>
                            </h4>
                        </div>
                    </div>
                </div>
                <div id="collapse1" class="panel-collapse collapse in">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-12">
                                <label class="col-md-3 text-right field-lable">Category</label>
                                <div class="col-md-6">
                                    <select id="SeriesCategoryId" asp-items="ViewBag.SeriesCategory">
                                        <option value="0">Select...</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <label class="col-md-3 text-right field-lable">Series</label>
                                <div class="col-md-6">
                                    <select id="SeriesId"></select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-4">
                                        <br />
                                        <input type="button" class="btn btn-sm btn-primary" name="searchBtn" value="Search" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                        <div class="row">
                        </div>
                    </div>
                    <div class="panel-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
<div class="content-area col-sm-9">
    <div class="detail-block">
        <div class="auction-block">
            <div class="table-responsive">
                <partial name="_Winners" model="Model" />
            </div>
        </div>
    </div>
</div>